"""lean_export.py -- the fourth format is not a rendering, it is a re-check.

Plaintext, Markdown, and LaTeX re-present what our checker said. Lean does not
trust our checker at all. It emits a self-contained proof script that RE-DERIVES
the certificate's property from the raw data, in a language neither the operator
nor the model authored, evaluated by the Lean toolchain. If the script compiles,
a checker we did not write has agreed. If it does not, they disagree, and the
disagreement is the finding.

This is the strongest held-out scorer in the whole system. A second Python
checker (`certificates/independent.py`) shares our language, our libraries, and
our machine. Lean shares none of those. The independence a size-invariant claim
needs comes from software the operator did not author, and this is the cleanest
instance of it available.

TWO HONESTIES THAT TRAVEL IN THE EMITTED FILE ITSELF.

  1. The emitted script ends with `#print axioms`, so the consumer reads the
     exact trust base rather than taking our word for it. Today the crossing and
     Zarankiewicz counts reduce through `native_decide`, which adds a
     compilation axiom: the check trusts Lean's compiler and the CPU, not only
     the kernel. That is a smaller and NAMED trust base than "trust our Python",
     and it is stated in the file. A pure-`decide` encoding, which would depend on
     no such axiom, is a future improvement and is noted in the header.

  2. Lean re-derives the property the certificate is ABOUT (the crossing count,
     K_{2,2}-freeness). It does not re-derive optimality, because nothing in this
     system does. The header says so, so a reader who compiles the file cannot
     mistake a checked count for a solved problem.

The emitted file imports nothing. A stranger with a Lean toolchain and no network
can check it.
"""
from __future__ import annotations

import json

# Vertices on a parabola or any generated instance stay small, but a coordinate
# is unbounded in principle. Lean's Int is arbitrary precision, so there is no
# overflow; this cap only keeps an emitted file from being absurdly large.
_MAX_POINTS = 4096


def _int_pairs(pairs) -> str:
    return "[" + ",".join(f"({int(a)},{int(b)})" for a, b in pairs) + "]"


def _nat_pairs(pairs) -> str:
    return "[" + ",".join(f"({int(a)},{int(b)})" for a, b in pairs) + "]"


_HEADER = (
    "-- Generated by flywheel lean_export. Self-contained: imports nothing, so a\n"
    "-- stranger with a Lean toolchain and no network can check it.\n"
    "--\n"
    "-- This RE-DERIVES the certificate's property in Lean. It does NOT re-derive\n"
    "-- optimality, because nothing in the system does: a checked count is not a\n"
    "-- solved problem. Read the `#print axioms` line at the end for the exact\n"
    "-- trust base. `native_decide` adds a compilation axiom (trusts Lean's\n"
    "-- compiler and the CPU); a pure-`decide` encoding would remove it.\n"
)


def crossing_lean(cert: dict) -> str:
    """A Lean script that re-counts the crossings of the submitted drawing."""
    coords = cert["coords"]
    edges = [(min(u, v), max(u, v)) for u, v in cert["edges"]]
    claimed = int(cert["crossings"])
    if len(coords) > _MAX_POINTS:
        raise ValueError(f"drawing has {len(coords)} points, over the emit cap "
                         f"{_MAX_POINTS}")
    return _HEADER + f"""
def orient (a b c : Int × Int) : Int :=
  (b.1 - a.1) * (c.2 - a.2) - (b.2 - a.2) * (c.1 - a.1)

def straddle (p q r s : Int × Int) : Bool :=
  decide ((orient p q r) * (orient p q s) < 0) &&
  decide ((orient r s p) * (orient r s q) < 0)

def getv (cs : List (Int × Int)) (i : Nat) : Int × Int := (cs[i]?).getD (0, 0)
def edgeAt (es : List (Nat × Nat)) (i : Nat) : Nat × Nat := (es[i]?).getD (0, 0)

def countCrossings (cs : List (Int × Int)) (es : List (Nat × Nat)) : Nat :=
  let n := es.length
  let ps := (List.range n).flatMap (fun i =>
    (List.range n).filterMap (fun j => if i < j then some (i, j) else none))
  ps.foldl (fun acc ij =>
    let e1 := edgeAt es ij.1
    let e2 := edgeAt es ij.2
    let a := e1.1; let b := e1.2; let c := e2.1; let d := e2.2
    if a == c || a == d || b == c || b == d then acc
    else if straddle (getv cs a) (getv cs b) (getv cs c) (getv cs d)
         then acc + 1 else acc) 0

def coords : List (Int × Int) := {_int_pairs(coords)}
def edges  : List (Nat × Nat) := {_nat_pairs(edges)}

-- The certificate claims this drawing has exactly {claimed} crossing pairs.
theorem cert_crossing_count : countCrossings coords edges = {claimed} := by native_decide
#print axioms cert_crossing_count
"""


def zarankiewicz_lean(cert: dict) -> str:
    """A Lean script that re-checks K_{2,2}-freeness of the submitted graph."""
    m = int(cert["m"])
    edges = [(int(u), int(v)) for u, v in cert["edges"]]
    return _HEADER + f"""
def nbrs (es : List (Nat × Nat)) (u : Nat) : List Nat :=
  (es.filter (fun e => e.1 == u)).map (fun e => e.2)

def commonCount (a b : List Nat) : Nat :=
  (a.filter (fun x => b.contains x)).length

def k22Free (m : Nat) (es : List (Nat × Nat)) : Bool :=
  (List.range m).all (fun u =>
    (List.range m).all (fun v =>
      if u < v then commonCount (nbrs es u) (nbrs es v) < 2 else true))

def edges : List (Nat × Nat) := {_nat_pairs(edges)}

-- The certificate claims this {m}-row bipartite graph is K_(2,2)-free.
theorem cert_k22_free : k22Free {m} edges = true := by native_decide
#print axioms cert_k22_free
"""


_EMITTERS = {
    "rectilinear_crossing": crossing_lean,
    "zarankiewicz": zarankiewicz_lean,
}


def family_of(result) -> str:
    """`cmd` is `<oracle_type>:<family>`; the family is the part that matters."""
    cmd = getattr(result, "cmd", "")
    return cmd.split(":", 1)[1] if ":" in cmd else cmd


def to_lean(result, cert: dict) -> str:
    fam = family_of(result)
    emit = _EMITTERS.get(fam)
    if emit is None:
        raise ValueError(
            f"no Lean export for family {fam!r}; a family earns a Lean export "
            "only once its predicate has a checked Lean encoding, so this refuses "
            f"rather than emitting a script that asserts nothing. Have: "
            f"{sorted(_EMITTERS)}")
    if _verdict_str(result) != "PASS":
        # A Lean script re-derives a property that HOLDS. Emitting one for a FAIL
        # would ask Lean to prove something false, which it correctly cannot, and
        # the compile error would read as a toolchain problem rather than as the
        # candidate's failure the oracle already recorded.
        raise ValueError(
            f"Lean export is for a PASS; this result is {_verdict_str(result)}. "
            "The FAIL is already on the oracle record.")
    return emit(cert)


def _verdict_str(result) -> str:
    v = result.verdict() if callable(getattr(result, "verdict", None)) else \
        getattr(result, "verdict", "")
    return str(v)


def lean_axioms(source: str, *, lean: str = "lean", timeout: int = 180) -> dict:
    """Run the emitted script through Lean, if a toolchain is present.

    Returns {ok, axioms, stderr}. `ok` is True only when Lean COMPILED it, which
    for these scripts means the property held. A missing toolchain returns
    ok=None with a note, never a false pass: absence of a checker is not a check.
    """
    import shutil
    import subprocess
    import tempfile
    from pathlib import Path

    if shutil.which(lean) is None:
        return {"ok": None, "axioms": [], "note": f"{lean} not on PATH; the "
                "emitted script was not checked here. It is self-contained and a "
                "stranger with a Lean toolchain can check it."}
    with tempfile.TemporaryDirectory() as d:
        p = Path(d) / "cert.lean"
        p.write_text(source, encoding="utf-8")
        try:
            r = subprocess.run([lean, str(p)], capture_output=True, text=True,
                               timeout=timeout)
        except subprocess.TimeoutExpired:
            return {"ok": None, "axioms": [], "note": f"lean did not finish in "
                    f"{timeout}s"}
    ok = r.returncode == 0
    axioms: list = []
    for line in (r.stdout or "").splitlines():
        if "depends on axioms:" in line:
            axioms = [a.strip() for a in
                      line.split("[", 1)[-1].rstrip("]").split(",") if a.strip()]
    return {"ok": ok, "axioms": axioms,
            "stderr": (r.stderr or "").strip()[:600] if not ok else ""}
